const MOCK_DATA = {
  eixos: [
    {
      id: 1, ordem: 1,
      nome: 'Documentos Normativos',
      descricao: 'Políticas Públicas de Educação Especial Inclusiva.',
      cor: '#1B5E4B', icone: 'file-shield',
      dica: 'Conhecer os documentos legais é o primeiro passo para garantir direitos e promover práticas pedagógicas inclusivas.'
    },
    {
      id: 2, ordem: 2,
      nome: 'Estratégias pedagógicas',
      descricao: 'Abordagens e práticas que promovem o ensino inclusivo e significativo, favorecendo o desenvolvimento de todos os estudantes.',
      cor: '#624693', icone: 'book-open',
      dica: 'Combine diferentes estratégias pedagógicas para atender às diversidades da sua turma.'
    },
    {
      id: 3, ordem: 3,
      nome: 'Atividades e recursos pedagógicos',
      descricao: 'Materiais e atividades adaptadas para diferentes necessidades e contextos, promovendo acessibilidade e participação.',
      cor: '#E8752A', icone: 'pencil-case',
      dica: 'Adapte as atividades às necessidades dos alunos, mantendo os objetivos de aprendizagem.'
    }
  ],
  categorias: [
    { id: 1, eixoid: 1, nome: 'Legislação e políticas', icone: 'scale', ordem: 1, totaldocumentos: 1 },
    { id: 2, eixoid: 1, nome: 'Diretrizes e orientações', icone: 'book-open', ordem: 2, totaldocumentos: 1 },
    { id: 3, eixoid: 1, nome: 'BNCC e currículo', icone: 'graduation-cap', ordem: 3, totaldocumentos: 1 },
    { id: 4, eixoid: 1, nome: 'Direitos e marcos legais', icone: 'gavel', ordem: 4, totaldocumentos: 0 },
    { id: 5, eixoid: 1, nome: 'Planos e normativas', icone: 'file-text', ordem: 5, totaldocumentos: 0 },
    { id: 16, eixoid: 1, nome: 'Artigos científicos, livros e estudos na área', icone: 'book-open', ordem: 6, totaldocumentos: 0 },
    { id: 6, eixoid: 2, nome: 'Ensino colaborativo', icone: 'users', ordem: 1, totaldocumentos: 1 },
    { id: 7, eixoid: 2, nome: 'Aprendizagem ativa', icone: 'lightbulb', ordem: 2, totaldocumentos: 1 },
    { id: 8, eixoid: 2, nome: 'Diferenciação pedagógica', icone: 'layers', ordem: 3, totaldocumentos: 1 },
    { id: 9, eixoid: 2, nome: 'Avaliação inclusiva', icone: 'clipboard-check', ordem: 4, totaldocumentos: 1 },
    { id: 10, eixoid: 2, nome: 'Metodologias ativas', icone: 'puzzle', ordem: 5, totaldocumentos: 0 },
    { id: 11, eixoid: 3, nome: 'Planos de aula adaptados', icone: 'calendar', ordem: 1, totaldocumentos: 1 },
    { id: 12, eixoid: 3, nome: 'Materiais imprimíveis', icone: 'printer', ordem: 2, totaldocumentos: 1 },
    { id: 13, eixoid: 3, nome: 'Vídeos e tutoriais', icone: 'play-circle', ordem: 3, totaldocumentos: 0 },
    { id: 14, eixoid: 3, nome: 'Recursos digitais', icone: 'monitor', ordem: 4, totaldocumentos: 1 },
    { id: 15, eixoid: 3, nome: 'Jogos e brincadeiras', icone: 'gamepad-2', ordem: 5, totaldocumentos: 1 }
  ],
  tags: [
    { id: 1, nome: 'PDF', cor: '#E8F5E9' },
    { id: 2, nome: 'Colaboração', cor: '#EDE7F6' },
    { id: 3, nome: 'Planejamento', cor: '#FFF3E0' },
    { id: 4, nome: 'Metodologia', cor: '#E3F2FD' },
    { id: 5, nome: 'Avaliação', cor: '#FCE4EC' },
    { id: 6, nome: 'Inclusão', cor: '#FFF3E0' },
    { id: 7, nome: 'Deficiência intelectual', cor: '#E8F5E9' },
    { id: 8, nome: 'Tecnologia assistiva', cor: '#E3F2FD' },
    { id: 9, nome: 'DA', cor: '#EDE7F6' },
    { id: 10, nome: 'Ensino colaborativo', cor: '#E8F5E9' }
  ],
  icone: [
    { id: 1, emoji: '📄', nome: 'file-shield', descricao: 'Escudo com documento' },
    { id: 2, emoji: '📖', nome: 'book-open', descricao: 'Livro aberto' },
    { id: 3, emoji: '✏️', nome: 'pencil-case', descricao: 'Estojo de lápis' },
    { id: 4, emoji: '⚖️', nome: 'scale', descricao: 'Balança' },
    { id: 5, emoji: '🎓', nome: 'graduation-cap', descricao: 'Capelo de formatura' },
    { id: 6, emoji: '⚖️', nome: 'gavel', descricao: 'Martelo de juiz' },
    { id: 7, emoji: '📝', nome: 'file-text', descricao: 'Documento com texto' },
    { id: 8, emoji: '👥', nome: 'users', descricao: 'Grupo de pessoas' },
    { id: 9, emoji: '💡', nome: 'lightbulb', descricao: 'Lâmpada de ideia' },
    { id: 10, emoji: '📚', nome: 'layers', descricao: 'Camadas empilhadas' },
    { id: 11, emoji: '✅', nome: 'clipboard-check', descricao: 'Prancheta com check' },
    { id: 12, emoji: '🧩', nome: 'puzzle', descricao: 'Quebra-cabeça' },
    { id: 13, emoji: '📅', nome: 'calendar', descricao: 'Calendário' },
    { id: 14, emoji: '🖨️', nome: 'printer', descricao: 'Impressora' },
    { id: 15, emoji: '▶️', nome: 'play-circle', descricao: 'Círculo com play' },
    { id: 16, emoji: '🖥️', nome: 'monitor', descricao: 'Monitor de computador' },
    { id: 17, emoji: '🎮', nome: 'gamepad-2', descricao: 'Controle de jogos' },
    { id: 18, emoji: '📁', nome: 'folder', descricao: 'Pasta' },
    { id: 19, emoji: '➡️', nome: 'chevron-right', descricao: 'Seta para direita' },
    { id: 20, emoji: '⬅️', nome: 'chevron-left', descricao: 'Seta para esquerda' },
    { id: 21, emoji: '🔔', nome: 'bell', descricao: 'Sino de notificação' },
    { id: 22, emoji: '🎯', nome: 'target', descricao: 'Alvo' },
    { id: 23, emoji: '⭐', nome: 'star', descricao: 'Estrela' },
    { id: 24, emoji: '👁️', nome: 'eye', descricao: 'Olho de visualização' },
    { id: 25, emoji: '🔖', nome: 'bookmark', descricao: 'Marcador' },
    { id: 26, emoji: '🔍', nome: 'search', descricao: 'Lupa de busca' },
    { id: 27, emoji: '🔽', nome: 'filter', descricao: 'Filtro' },
    { id: 28, emoji: '➡️', nome: 'arrow-right', descricao: 'Seta direita' },
    { id: 29, emoji: '🗑️', nome: 'trash-2', descricao: 'Lixeira' },
    { id: 30, emoji: '⚖️', nome: 'balanca-juridica', descricao: 'Balança — Legislação geral e pareceres jurídicos' },
    { id: 31, emoji: '📜', nome: 'pergaminho', descricao: 'Pergaminho — Leis federais (LDB, ECA, Estatuto da Pessoa com Deficiência)' },
    { id: 32, emoji: '📕', nome: 'livro-vermelho', descricao: 'Livro vermelho — Código Civil, Constituição ou regimento interno' },
    { id: 33, emoji: '🏛️', nome: 'predio-constitucional', descricao: 'Prédio constitucional — Decisões de tribunais, Ministério Público' },
    { id: 34, emoji: '👨\u200D⚖️', nome: 'juiz', descricao: 'Juiz — Sentenças judiciais, liminares e mandados de segurança' },
    { id: 35, emoji: '👩\u200D⚖️', nome: 'juiza', descricao: 'Juíza — Atas de audiência e determinações do Poder Judiciário' },
    { id: 36, emoji: '🛡️', nome: 'escudo', descricao: 'Escudo — Medidas de proteção ao menor, garantias legais' },
    { id: 37, emoji: '📑', nome: 'separadores', descricao: 'Separadores — Decretos, portarias normativas e emendas' },
    { id: 38, emoji: '✒️', nome: 'caneta-tinteiro', descricao: 'Caneta tinteiro — Assinatura de termos de ajustamento de conduta (TAC)' },
    { id: 39, emoji: '🖋️', nome: 'caneta-estilografica', descricao: 'Caneta estilográfica — Contratos de prestação de serviços e convênios legais' },
    { id: 40, emoji: '🔏', nome: 'cadeado-caneta', descricao: 'Cadeado com caneta — Termos de confidencialidade e LGPD' },
    { id: 41, emoji: '🔒', nome: 'cadeado-fechado', descricao: 'Cadeado fechado — Segredo de justiça, processos sigilosos' },
    { id: 42, emoji: '🔓', nome: 'cadeado-aberto', descricao: 'Cadeado aberto — Documentos de domínio público' },
    { id: 43, emoji: '🤝', nome: 'aperto-maos', descricao: 'Aperto de mãos — Acordos extrajudiciais, mediações' },
    { id: 44, emoji: '🗣️', nome: 'megafone', descricao: 'Megafone — Denúncias formais, ouvidoria' },
    { id: 45, emoji: '🚫', nome: 'proibido', descricao: 'Proibido — Notificações de infrações, penalidades' },
    { id: 46, emoji: '⚠️', nome: 'alerta', descricao: 'Alerta — Notificações de urgência judicial' },
    { id: 47, emoji: '📅', nome: 'calendario-prazo', descricao: 'Calendário com prazo — Prazos legais para cumprimento de decisões' },
    { id: 48, emoji: '📬', nome: 'caixa-correio', descricao: 'Caixa de correio — Citações, intimações e notificações oficiais' },
    { id: 49, emoji: '📝', nome: 'memorial', descricao: 'Memorial — Petições, defesas administrativas' },
    { id: 50, emoji: '🧩', nome: 'quebra-cabeca-TEA', descricao: 'Quebra-cabeça — Documentos, laudos e triagens de estudantes com TEA' },
    { id: 51, emoji: '🧠', nome: 'cerebro', descricao: 'Cérebro — Laudos de neurodivergências (TDAH, Dislexia, Discalculia, TOD)' },
    { id: 52, emoji: '♿', nome: 'cadeira-rodas', descricao: 'Cadeira de rodas — Acessibilidade arquitetônica e laudos de deficiência motora' },
    { id: 53, emoji: '🤟', nome: 'te-amo', descricao: 'Sinal de Te Amo — Recursos de acessibilidade em Libras e cultura surda' },
    { id: 54, emoji: '👂', nome: 'ouvido-aparelho', descricao: 'Ouvido com aparelho — Deficiência auditiva e uso de tecnologias (AASI/IC)' },
    { id: 55, emoji: '🧏', nome: 'pessoa-surda', descricao: 'Pessoa surda — Relatórios de intérpretes e tradutores de Libras oficiais' },
    { id: 56, emoji: '🦯', nome: 'bengala-branca', descricao: 'Bengala branca — Documentos de estudantes com deficiência visual ou cegueira' },
    { id: 57, emoji: '👁️', nome: 'olho-adaptacoes', descricao: 'Olho — Adaptações de layout (textos ampliados ou material em Braille)' },
    { id: 58, emoji: '🐕\u200D🦺', nome: 'cao-guia', descricao: 'Cão-guia — Autorizações legais para o trânsito de animais de assistência' },
    { id: 59, emoji: '👣', nome: 'pegadas', descricao: 'Pegadas — Relatórios de evolução psicomotora e fisioterapia' },
    { id: 60, emoji: '🌈', nome: 'arco-iris', descricao: 'Arco-íris — Transtornos globais do desenvolvimento e neurodiversidade geral' },
    { id: 61, emoji: '💡', nome: 'lampada-ahsd', descricao: 'Lâmpada — Estudantes com Altas Habilidades / Superdotação identificados' },
    { id: 62, emoji: '🧬', nome: 'dna', descricao: 'DNA — Laudos de síndromes genéticas estruturais (Síndrome de Down, etc.)' },
    { id: 63, emoji: '🤍', nome: 'coracao-branco', descricao: 'Coração branco — Declarações e laudos de Deficiência Intelectual (DI)' },
    { id: 64, emoji: '🛠️', nome: 'ferramentas', descricao: 'Ferramentas — Adaptações de mobiliário ou recursos de Tecnologia Assistiva' },
    { id: 65, emoji: '🌱', nome: 'broto', descricao: 'Broto — Relatórios de evolução contínua do Plano de Atendimento (PAE)' },
    { id: 66, emoji: '🎨', nome: 'paleta', descricao: 'Paleta de tintas — Relatórios técnicos de Terapia Ocupacional' },
    { id: 67, emoji: '🗣️', nome: 'cabeca-falando', descricao: 'Cabeça falando — Pareceres analíticos de Fonoaudiologia' },
    { id: 68, emoji: '🧸', nome: 'urso-pelucia', descricao: 'Urso de pelúcia — Relatórios e manejos de Psicologia Infantil' },
    { id: 69, emoji: '🏥', nome: 'hospital', descricao: 'Hospital — Encaminhamentos oficiais para a rede de saúde (SUS, CAPS)' },
    { id: 70, emoji: '📄', nome: 'folha-branco', descricao: 'Folha em branco — Arquivos textuais simples, ofícios e circulares' },
    { id: 71, emoji: '📂', nome: 'pasta-aberta', descricao: 'Pasta aberta — Prontuário digital unificado do estudante' },
    { id: 72, emoji: '📋', nome: 'prancheta', descricao: 'Prancheta — Fichas cadastrais e requerimentos de matrícula' },
    { id: 73, emoji: '📜', nome: 'diploma', descricao: 'Diploma — Histórico escolar, certidões de conclusão e diplomas' },
    { id: 74, emoji: '📊', nome: 'grafico', descricao: 'Gráfico de barras — Boletins de notas e relatórios quantitativos de desempenho' },
    { id: 75, emoji: '🗓️', nome: 'calendario-letivo', descricao: 'Calendário — Calendário letivo e registros de cumprimento de carga horária' },
    { id: 76, emoji: '📥', nome: 'caixa-entrada', descricao: 'Caixa de entrada — Upload de novos arquivos aguardando validação interna' },
    { id: 77, emoji: '🆔', nome: 'botao-id', descricao: 'Botão ID — Documentos pessoais obrigatórios (RG, CPF, Certidão de Nascimento)' },
    { id: 78, emoji: '📷', nome: 'camera', descricao: 'Câmera — Foto oficial do aluno para o sistema de identificação' },
    { id: 79, emoji: '✉️', nome: 'envelope', descricao: 'Envelope — Correspondências e avisos formais enviados aos responsáveis' },
    { id: 80, emoji: '📌', nome: 'taxinha', descricao: 'Taxinha — Avisos de extrema importância fixados no topo do prontuário' },
    { id: 81, emoji: '📎', nome: 'clipe', descricao: 'Clipe de papel — Adendos contratuais ou documentos anexos secundários' },
    { id: 82, emoji: '🖨️', nome: 'impressora-doc', descricao: 'Impressora — Documentos validados prontos para emissão física' },
    { id: 83, emoji: '🔍', nome: 'lupa-auditoria', descricao: 'Lupa — Auditorias de documentos ou processos em fase de verificação' },
    { id: 84, emoji: '🗂️', nome: 'divisorias', descricao: 'Divisórias de fichário — Organização de arquivos por anos letivos anteriores' },
    { id: 85, emoji: '✔️', nome: 'verificacao', descricao: 'Marca de verificação — Documentação homologada e totalmente regularizada' },
    { id: 86, emoji: '❌', nome: 'xis-vermelho', descricao: 'Xis vermelho — Documentação rejeitada, vencida ou com pendências' },
    { id: 87, emoji: '🔄', nome: 'setas-rotacao', descricao: 'Setas de rotação — Documentos que precisam de renovação periódica (ex: laudos)' },
    { id: 88, emoji: '💼', nome: 'pasta-trabalho', descricao: 'Pasta de trabalho — Documentos funcionais de professores e corpo técnico' },
    { id: 89, emoji: '✍️', nome: 'mao-escrevendo', descricao: 'Mão escrevendo — Atas de reuniões pedagógicas e conselhos de classe' },
    { id: 90, emoji: '🍼', nome: 'mamadeira', descricao: 'Mamadeira — Matrículas e rotinas do Berçário' },
    { id: 91, emoji: '👶', nome: 'bebe', descricao: 'Bebê — Documentação da Educação Infantil (Creche)' },
    { id: 92, emoji: '🧒', nome: 'crianca', descricao: 'Criança — Documentos do Ensino Fundamental I (Anos Iniciais)' },
    { id: 93, emoji: '🧑', nome: 'adolescente', descricao: 'Adolescente — Documentos do Ensino Fundamental II (Anos Finais)' },
    { id: 94, emoji: '🧑\u200D🎓', nome: 'estudante', descricao: 'Estudante — Documentos do Ensino Médio' },
    { id: 95, emoji: '🎒', nome: 'mochila', descricao: 'Mochila — Listas de materiais e termos de uso de uniforme' },
    { id: 96, emoji: '🏫', nome: 'escola', descricao: 'Escola — Projetos Político-Pedagógicos (PPP) institucionais' },
    { id: 97, emoji: '🚌', nome: 'onibus-escolar', descricao: 'Ônibus escolar — Autorizações de transporte escolar e viagens de estudo' },
    { id: 98, emoji: '🍽️', nome: 'prato', descricao: 'Prato e talheres — Mapeamento de restrições alimentares e merenda' },
    { id: 99, emoji: '🏡', nome: 'casa', descricao: 'Casa — Pareceres sobre Ensino Domiciliar ou estudantes em regime hospitalar' },
    { id: 100, emoji: '⏰', nome: 'relogio', descricao: 'Relógio — Controle rigoroso de frequência, faltas e atrasos' },
    { id: 101, emoji: '🌅', nome: 'sol-nascente', descricao: 'Sol nascente — Documentos vinculados ao Turno Matutino' },
    { id: 102, emoji: '🌇', nome: 'por-do-sol', descricao: 'Pôr do sol — Documentos vinculados ao Turno Vespertino' },
    { id: 103, emoji: '🌃', nome: 'noite-estrelada', descricao: 'Noite estrelada — Documentos vinculados à EJA (Educação de Jovens e Adultos)' },
    { id: 104, emoji: '👟', nome: 'tenis', descricao: 'Tênis de corrida — Práticas esportivas e relatórios de Educação Física' },
    { id: 105, emoji: '🩺', nome: 'estetoscopio', descricao: 'Estetoscópio — Autorizações médicas para atividades físicas severas' },
    { id: 106, emoji: '💊', nome: 'pillula', descricao: 'Pílula — Termos de autorização para administração de remédios na rotina' },
    { id: 107, emoji: '🩹', nome: 'curativo', descricao: 'Curativo — Prontuário de primeiros socorros e ocorrências escolares' },
    { id: 108, emoji: '🍎', nome: 'maca', descricao: 'Maçã vermelha — Declarações de alergias alimentares graves' },
    { id: 109, emoji: '💬', nome: 'balao-conversa', descricao: 'Balão de conversa — Anamneses e entrevistas formais com a família' },
    { id: 110, emoji: '✏️', nome: 'lapis-alfabetizacao', descricao: 'Lápis — Alfabetização e relatórios de escrita inicial' },
    { id: 111, emoji: '📚', nome: 'livros', descricao: 'Livros — Fichas de leitura e projetos da biblioteca' },
    { id: 112, emoji: '📐', nome: 'esquadro', descricao: 'Esquadro e régua — Produções de matemática e geometria' },
    { id: 113, emoji: '🔬', nome: 'microscopio', descricao: 'Microscópio — Relatórios de laboratório de ciências' },
    { id: 114, emoji: '🗺️', nome: 'mapa-mundi', descricao: 'Mapa-múndi — Trabalhos e projetos de geografia e história' },
    { id: 115, emoji: '🎵', nome: 'nota-musical', descricao: 'Nota musical — Oficinas de música e expressões rítmicas' },
    { id: 116, emoji: '🖼️', nome: 'quadro', descricao: 'Quadro moldurado — Portfólios de artes visuais dos alunos' },
    { id: 117, emoji: '💻', nome: 'computador', descricao: 'Computador — Atividades de informática ou uso de plataformas digitais' },
    { id: 118, emoji: '🧮', nome: 'abaco', descricao: 'Ábaco — Estimulação cognitiva e matemática básica estruturada' },
    { id: 119, emoji: '🎭', nome: 'mascaras', descricao: 'Máscaras de teatro — Projetos de expressão corporal e artes cênicas' },
    { id: 120, emoji: '♟️', nome: 'peao-xadrez', descricao: 'Peão de xadrez — Oficinas de raciocínio lógico e jogos de tabuleiro' },
    { id: 121, emoji: '🚀', nome: 'foguete', descricao: 'Foguete — Projetos de astronomia, robótica ou feiras científicas' },
    { id: 122, emoji: '🌳', nome: 'arvore', descricao: 'Árvore — Projetos e relatórios de educação ambiental' },
    { id: 123, emoji: '💵', nome: 'cedula', descricao: 'Cédula de dólar — Projetos transversais de educação financeira' },
    { id: 124, emoji: '🇺🇸', nome: 'bandeira-eua', descricao: 'Bandeira EUA — Registros de proficiência ou aulas de língua inglesa' },
    { id: 125, emoji: '🗣️', nome: 'rosto-falando', descricao: 'Rosto falando — Avaliações de produções orais e debates' },
    { id: 126, emoji: '🍳', nome: 'frigideira', descricao: 'Frigideira — Oficinas de culinária pedagógica para desenvolvimento de autonomia' },
    { id: 127, emoji: '🌱', nome: 'planta-jovem', descricao: 'Planta jovem — Projetos de horta escolar e biologia prática' },
    { id: 128, emoji: '🎯', nome: 'alvo-pdi', descricao: 'Alvo — Relatórios de atingimento de metas do PDI/PEI' },
    { id: 129, emoji: '🏆', nome: 'trofeu', descricao: 'Troféu — Registros de premiações e destaques acadêmicos' },
    { id: 130, emoji: '📝', nome: 'memorial-recursos', descricao: 'Memorial — Petições, defesas administrativas e recursos escolares' }
  ],
  documentos: [
    { id: 1, categoriaid: 1, eixoid: 1, titulo: 'Lei Brasileira de Inclusão da Pessoa com Deficiência', descricao: 'Lei que garante os direitos das pessoas com deficiência.', url: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13146.htm', tipo: 'PDF', autor_origem: 'Lei nº 13.146/2015', iconeid: 31, tags: [{ nome: 'PDF', cor: '#E8F5E9' }] },
    { id: 2, categoriaid: 1, eixoid: 1, titulo: 'Política Nacional de Educação Especial na Perspectiva da Educação Inclusiva', descricao: 'Documento que orienta a educação especial inclusiva no Brasil.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'PDF', autor_origem: 'Ministério da Educação', iconeid: 33, tags: [{ nome: 'PDF', cor: '#E8F5E9' }] },
    { id: 3, categoriaid: 3, eixoid: 1, titulo: 'Base Nacional Comum Curricular (BNCC)', descricao: 'Documento que define o conjunto orgânico de aprendizagens essenciais.', url: 'http://basenacionalcomum.mec.gov.br/', tipo: 'site', autor_origem: 'Ministério da Educação', iconeid: 37, tags: [] },
    { id: 4, categoriaid: 2, eixoid: 1, titulo: 'Orientações para a Implementação da Educação Inclusiva', descricao: 'Orientações práticas para implementação da educação inclusiva nas escolas.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'PDF', autor_origem: 'Ministério da Educação', iconeid: 49, tags: [{ nome: 'PDF', cor: '#E8F5E9' }] },
    { id: 5, categoriaid: 6, eixoid: 2, titulo: 'Ensino Colaborativo', descricao: 'Estratégia que promove a interação entre pares com e sem deficiência.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'site', autor_origem: 'PROFEI/UERN', iconeid: 43, tags: [{ nome: 'Colaboração', cor: '#EDE7F6' }] },
    { id: 6, categoriaid: 7, eixoid: 2, titulo: 'Aprendizagem Baseada em Projetos', descricao: 'Metodologia que envolve os estudantes em projetos reais e significativos.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'site', autor_origem: 'PROFEI/UERN', iconeid: 61, tags: [{ nome: 'Metodologia', cor: '#E3F2FD' }] },
    { id: 7, categoriaid: 8, eixoid: 2, titulo: 'Diferenciação Pedagógica na Prática', descricao: 'Como adaptar ensino, conteúdo e avaliação para atender a todos.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'site', autor_origem: 'PROFEI/UERN', iconeid: 50, tags: [{ nome: 'Planejamento', cor: '#FFF3E0' }] },
    { id: 8, categoriaid: 9, eixoid: 2, titulo: 'Avaliação Inclusiva: Princípios e Práticas', descricao: 'Princípios para uma avaliação que considera as diversidades.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'site', autor_origem: 'PROFEI/UERN', iconeid: 85, tags: [{ nome: 'Avaliação', cor: '#FCE4EC' }] },
    { id: 9, categoriaid: 14, eixoid: 3, titulo: 'Comunicação Alternativa em Sala de Aula', descricao: 'Recursos e estratégias de comunicação alternativa para estudantes com necessidades específicas.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'site', autor_origem: 'PROFEI/UERN', iconeid: 52, tags: [{ nome: 'Inclusão', cor: '#FFF3E0' }, { nome: 'Tecnologia assistiva', cor: '#E3F2FD' }] },
    { id: 10, categoriaid: 11, eixoid: 3, titulo: 'Atividades de Matemática Adaptadas', descricao: 'Sequências didáticas de matemática adaptadas para diferentes necessidades.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'PDF', autor_origem: 'PROFEI/UERN', iconeid: 118, tags: [{ nome: 'Inclusão', cor: '#FFF3E0' }, { nome: 'DA', cor: '#EDE7F6' }] },
    { id: 11, categoriaid: 12, eixoid: 3, titulo: 'Cartões de Comunicação Visual', descricao: 'Materiais imprimíveis para comunicação aumentativa e alternativa.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'PDF', autor_origem: 'PROFEI/UERN', iconeid: 53, tags: [{ nome: 'Deficiência intelectual', cor: '#E8F5E9' }] },
    { id: 12, categoriaid: 15, eixoid: 3, titulo: 'Jogos Cooperativos Inclusivos', descricao: 'Atividades lúdicas que promovem a participação de todos os estudantes.', url: 'https://www.gov.br/mec/pt-br/escolas-educacao-basica/educacao-especial', tipo: 'site', autor_origem: 'PROFEI/UERN', iconeid: 120, tags: [{ nome: 'Ensino colaborativo', cor: '#E8F5E9' }] }
  ]
};

const DICAS_EDUCACAO = [
  'Conhecer os documentos legais é o primeiro passo para garantir direitos e promover práticas pedagógicas inclusivas.',
  'Combine diferentes estratégias pedagógicas para atender às diversidades da sua turma.',
  'Adapte as atividades às necessidades dos alunos, mantendo os objetivos de aprendizagem.',
  'A adaptação curricular não é reduzir conteúdo, mas adequar objetivos às necessidades individuais.',
  'Use recursos multissensoriais para tornar o conteúdo acessível a todos os alunos.',
  'Avaliações inclusivas devem considerar diferentes formas de demonstrar o conhecimento.',
  'A comunicação alternativa e aumentativa é uma ferramenta poderosa para inclusão.',
  'Planeje aulas com flexibilidade — a diversidade é uma oportunidade de aprendizado.',
  'Tecnologias assistivas podem transformar a experiência de aprendizagem dos alunos.',
  'Inclua atividades em grupo que promovam interação e valorização das diferenças.',
  'A formação continuada do professor é fundamental para educação inclusiva de qualidade.',
  'Documente as adaptações realizadas para garantir continuidade do acompanhamento pedagógico.',
  'Ouvir o aluno e sua família é essencial para planejar intervenções eficazes.',
  'Utilize recursos visuais e concretos para facilitar a compreensão de conceitos abstratos.',
  'Promova a autonomia dos alunos com deficiência estimulando a tomada de decisão.',
  'O ambiente de aprendizagem deve ser acessível física e pedagogicamente.',
  'A individualização do ensino não significa perder o ritmo da turma como um todo.',
  'Parcerias com profissionais especializados enriquecem o processo de inclusão.',
  'Celebre pequenas conquistas — cada avanço é um passo em direção à inclusão.',
  'Conheça as deficiências e necessidades dos seus alunos para oferecer o melhor suporte.',
  'A inclusão começa na atitude: tratamento respeitoso e igualdade de oportunidades.',
];
